version: '3.8'

services:

  # Nginx Service
  reverse-proxy:
    image: nginx:alpine
    restart: always
    ports:
      - "8080:80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 20M
    depends_on:
      - wordpress
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
       - hostnetwork

  # MySQL Service
  db:
    image: mysql:5.7
    volumes:
      - ./${DIR}/db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mywordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
       - hostnetwork


  #WordPress Service
  wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
      - ./${DIR}/wordpress-data:/var/www/html
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
     networks:
        - hostnetwork

networks:
  hostnetwork:
     driver: bridge

